// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain



AppendStructuredBuffer<float4> points;
RWTexture2D<float4> Result;

int numPointsPerAxis;

int indexFromCoord(int x, int y, int z) {
    return z * numPointsPerAxis * numPointsPerAxis + y * numPointsPerAxis + x;
}


[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    
}
